NIFCLOUD-mbaas/ncmb_unity

ncmb_unity/Assets/NCMB/NCMBManager.cs
- Fixed #23 
- 5.3.5f1でエラーが出ないことを確認
=> fix build error for 5.3.5f1

Readme.md
* 環境設定に注意書きを追記しました
* ドキュメントから動作環境項目を削除することになりました。それに伴う変更です。
=> update README "環境設定"

ncmb_unity/Assets/Editor/NCMBUserTest.cs
=> add SNS_integration Test

ncmb_unity/Assets/Editor/NCMBPushTest.cs, ncmb_unity/Assets/NCMB/NCMBPush.cs
=> add search condtion to NCMB.Push

ncmb_unity/Assets/Editor/NCMBUserTest.cs, ncmb_unity/Assets/NCMB/NCMBFacebookParameters.cs, ncmb_unity/Assets/NCMB/NCMBObject.cs, ncmb_unity/Assets/NCMB/NCMBTwitterParameters.cs, ncmb_unity/Assets/NCMB/NCMBUser.cs
* Facebook, TwitterのSNS連携機能追加
* TestコードのGoogleのコメントアウト
* NCMBObjectのコード変更のため、NCMBUserTestにSignUpAsyncTestを追加
* NCMBUserTestの実行
* Testする際には下記リンクのstubサーバーを用いる
* https://github.com/NIFTYCloud-mbaas/ncmb_stub_server/tree/add/signin_code
* （Testする際にはScriptTest_Serverをどこかにmvしてから行なう）
=> add sns integration function

ncmb_unity/Assets/NCMB/NCMBConnection.cs
=> Add header info of sdk version

Readme.md, ncmb_unity/Assets/NCMB/CommonConstant.cs
- Readme.mdの更新
- CommonConstant.csのNCMBバージョンの更新
=> update Readme and NCMB version

ncmb_unity/Assets/NCMBSettings.cs
=> add reference params for initialize method

ncmb_unity/Assets/NCMBSettings.cs
- NCMBSettingsのdomainURLとapiVersionのSerializeFieldの削除
- プロパティのAPIVersionをpublicからinternalに変更
=> fix settings serialize field

ncmb_unity/Assets/NCMB/CommonConstant.cs
=> fix update sdk version number

ncmb_unity/Assets/NCMBManager.cs
- Fixed #133186
プッシュアプリを作成して、イベントリスナーを登録します。
アプリを起動して、端末をサーバーに登録完了したらOnRegistrationを呼ばれることを確認
=> call OnRegistration when regist device successful

ncmb_unity/Assets/Plugins/Android/AndroidManifest.xml
- Fixed #135979
APKファイルをビルドできることを確認
=> aarでビルドできるように修正します

ncmb_unity/Assets/Plugins/iOS/NCMBRichPushView.m
- Fixed #138406
- Run the unit test.
- Confirm operation.
=> 【iOS】二回目リッチプッシュ通知を配信場合リッチビューが表示されない

ncmb_unity/Assets/NCMB/NCMBConnection.cs
- Fixed https://github.com/NIFTYCloud-mbaas/ncmb_ios/issues/44
- Run the unit test.
- Confirm operation.
=> スクリプトのシグネチャロジックの変更

Readme.md
=> URL changes for github

ncmb_unity/Assets/NCMB/CommonConstant.cs
=> Update SDK version number

ncmb_unity/Assets/Plugins/iOS/NCMBAppControllerPushAdditions.mm
- Fixed #102 
- Confirmation for silent push:
1. Send a silent push notification by control panel.
→ Device receive push and go to handleRichPushIfReady (in Plugins/iOS/NCMBAppControllerPushAdditions.m ) method without crash
- Confirmation for normal push:
1. Send a normal push notification by control panel.
→ Device receive push and go to handleRichPushIfReady (in Plugins/iOS/NCMBAppControllerPushAdditions.m ) method without crash
=> プッシュ通知を設定する際メッセージとタイトルをnullで指定する場合クラッシュになる不具合を修正

ncmb_unity/Assets/PlayModeTest/NCMBAnalyticsTest.cs, ncmb_unity/Assets/PlayModeTest/NCMBConnectionTest.cs, ncmb_unity/Assets/PlayModeTest/NCMBInstallationTest.cs, ncmb_unity/Assets/PlayModeTest/NCMBPushTest.cs, ncmb_unity/Assets/PlayModeTest/NCMBScriptTest.cs, ncmb_unity/Assets/PlayModeTest/NCMBUserTest.cs
=> PlayModeTestフォルダ内の不要コード削除

ncmb_unity/Assets/NCMB/Script/NCMBConnection.cs, ncmb_unity/Assets/NCMB/Script/NCMBUser.cs
- Fixed #108
Confirm operation.
=> 最新の Unity SDK での実機ログインできないバグを修正

ncmb_unity/Assets/NCMB/NCMBManager.cs, ncmb_unity/Assets/NCMB/Script/NCMBInstallation.cs
=> NCMBInstallationでMonoBehaviourを継承したクラスをnewしようとしている部分の修正

ncmb_unity/Assets/NCMB/Script/NCMBUser.cs, ncmb_unity/Assets/PlayModeTest/MockServer.cs, ncmb_unity/Assets/PlayModeTest/NCMBTestSettings.cs, ncmb_unity/Assets/PlayModeTest/NCMBUserTestLogoutError.cs, ncmb_unity/Assets/PlayModeTest/json/logout_script_expired_session_respone.json, ncmb_unity/Assets/PlayModeTest/mbaasErrors.yaml
- Fixed:  loginAsync() and logoutAsync() Throw exception when the token has expired.
Implement the app and Manual test.
=> ログインとログアウト時にREST API が認証エラーを返してきた場合のみ Exception を発生しないようにする

Readme.md
=> サポート対応バージョン記載

ncmb_unity/Assets/NCMB/Script/CommonConstant.cs
=> Update version to 4.0.0

Readme.md
=> fix Readme iOS version

Readme.md
=> fix ReadMe android available versions

ncmb_unity/Assets/NCMB/Script/NCMBUser.cs
- Fixed #133 
- Run the unit test
- Confirm operation.
=> Implementation of anonymous authentication of Unity SDK

ncmb_unity/Assets/NCMB/Script/CommonConstant.cs
=> Update SDK version to v.4.0.1

ncmb_unity/Assets/NCMB/Script/NCMBUser.cs, ncmb_unity/Assets/PlayModeTest/NCMBUserTest.cs
- Fixed #143
SDKのバージョン(SDK version): v.4.0.0
不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
以下の手順を実施すると、エラーが発生することを確認しています。
登録済みの会員にログインする
ユーザー情報を取得し、何らかのデータを更新する。（SaveAsync()を実施）
データストアの適当なクラスに検索する。（FindAsync()を実施すると以下のエラーが発生する）
=> issue #143 Request error occurs after updating logged in user

Readme.md
=> UPDATE README: 動作環境の更新 201912

ncmb_unity/Assets/NCMB/Script/NCMBUser.cs, ncmb_unity/Assets/PlayModeTest/NCMBUserTest.cs, ncmb_unity/Assets/PlayModeTest/json/valid_post_registerUserFacebook_response200.json, ncmb_unity/Assets/PlayModeTest/json/valid_post_registerUserTwitter_response200.json, ncmb_unity/Assets/PlayModeTest/json/valid_post_signupUser_response.json, ncmb_unity/Assets/PlayModeTest/mbaas.yaml
- Fixed #161
- Run the unit test
- Confirm operation.
=> #161: 【SNS認証機能】既に認証して登録した会員で、アプリを再インストールし、再度認証してログインを実施するとcurrentUserがnullになります

ncmb_unity/Assets/NCMB/Script/NCMBUser.cs, ncmb_unity/Assets/PlayModeTest/NCMBUserTest.cs
=> Issue #161: Save currentUser when authenticate by sns

ncmb_unity/Assets/Plugins/iOS/NCMBRichPushView.h, ncmb_unity/Assets/Plugins/iOS/NCMBRichPushView.m
- Fixed #xx
iOS （iOS 13, 11）端末で以下の動作検証を行いました
- 端末登録
- リッチプッシュ通知の配信と受信の挙動
=> Update rich push to WKWebview based on iOS SDK 3.0.3

LICENSE, ncmb_unity/Assets/NCMB/Script/NCMBAppleAuthenManager.cs, ncmb_unity/Assets/Plugins/iOS/NCMBAppleAuth.h, ncmb_unity/Assets/Plugins/iOS/NCMBAppleAuth.m
=> Feature add license

Readme.md
=> SDK共通フォーマットに合わせてREADME更新

ncmb_unity/Assets/NCMB/Script/NCMBPush.cs
- Fixed #20 
- レファレンスのドキュメントも必要
=> fix #20: Update function explanation for NCMBPush getQuery()

Readme.md, ncmb_unity/Assets/NCMB/Script/CommonConstant.cs
=> Feature/release prepare v4.3.0

Readme.md
Update environment information
=> update environment information

Readme.md
update environment information
=> update readme's environment information

Readme.md, ncmb_unity/Assets/NCMB/Script/CommonConstant.cs
=> feature release prepare v4.4.0

Readme.md, ncmb_unity/Assets/NCMB/Script/CommonConstant.cs
=> READMEとバージョン変更（リリース準備 v4.4.1）

ncmb_unity/Assets/NCMB/PlayModeTest/NCMBTestSettings.cs, ncmb_unity/Assets/NCMB/Script/NCMBConnection.cs
- Fixed #120 
Unit testを実施ました。
問題ないのを確認しました。
=> change WaitForSeconds() to WaitForSecondsRealtime()

Readme.md, ncmb_unity/Assets/NCMB/Script/CommonConstant.cs
=> Release prepare v4.5.0

Readme.md
=> update readme for ios16

ncmb_unity/Assets/NCMB/Script/NCMBConnection.cs
=> Fix bug memory error on Unity 2021

.github/workflows/reference.yml
=> #249 の再テスト

ncmb_unity/Assets/Editor/PreBuildAndroid.cs, ncmb_unity/Assets/Editor/UpdateXcodeProject.cs, ncmb_unity/Assets/Plugins/Android/AndroidManifest.xml, ncmb_unity/Assets/Scenes/Member/Loginsignin.cs, ncmb_unity/Assets/Scenes/Member/Logout.cs
=> UnitySDK v4.5.0から発生していた警告の修正

Readme.md, ncmb_unity/Assets/NCMB/Script/CommonConstant.cs, ncmb_unity/Assets/package.json
=> Bump version to v5.0.0

ncmb_unity/Assets/NCMB/Script/NCMBUser.cs, ncmb_unity/Assets/NCMB/Script/Task/NCMBUserTaskMethods.cs, ncmb_unity/Assets/PlayModeTest/mbaas.yaml, ncmb_unity/Assets/PlayModeTest/mbaasErrors.yaml
=> POSTメソッドでの会員ログインを実装

ncmb_unity/Packages/manifest.json, ncmb_unity/Packages/packages-lock.json, ncmb_unity/ProjectSettings/ProjectVersion.txt
=> Unity2022対応

Readme.md, ncmb_unity/Assets/NCMB/Script/CommonConstant.cs, ncmb_unity/Assets/package.json
=> Bump version to v5.1.0

Readme.md, ncmb_unity/Assets/NCMB/Script/CommonConstant.cs, ncmb_unity/Assets/package.json
- Release preparation: Update version string
=> Bump to version v5.1.1

ncmb_unity/Assets/NCMB/Script/NCMBAppleParameters.cs, ncmb_unity/Assets/NCMB/Script/NCMBUser.cs
- Fixed #270 
- エラーが発生しないことを確認済み
- SignInWithApple機能も正常に動作したことを確認済み
=> Package Managerで導入すると、SignInWithApple 機能がエラーになっている不具合修正

Readme.md
=> サポート環境にiOS17を追加

ncmb_unity/Assets/Plugins.meta, ncmb_unity/Assets/Plugins/iOS.meta
- fix #275
-  plugin/iosフォルダ関連のファイルは.metaファイルをあげて、gitで管理する
=> plugin/ios meta ファイルの追加
